// Code generated by cmd/genclaudeflags from claude 2.1.259 --help; DO NOT EDIT.
// Regenerate with `go generate ./...` against a matching claude binary.

package main

// PinnedClaudeVersion is the claude CLI version this arity table mirrors.
// cc-adapter parses argv exactly as this version does; running it against a
// different claude may misclassify flags it added or removed.
const PinnedClaudeVersion = "2.1.259"

// forwardSingleValue: consume exactly the next token as the flag's value.
var forwardSingleValue = map[string]bool{
	"--advisor":                            true,
	"--agent":                              true,
	"--agent-color":                        true,
	"--agent-id":                           true,
	"--agent-name":                         true,
	"--agent-type":                         true,
	"--agents":                             true,
	"--append-subagent-system-prompt":      true,
	"--append-system-prompt":               true,
	"--append-system-prompt-file":          true,
	"--autocompact":                        true,
	"--correlation-id":                     true,
	"--debug-file":                         true,
	"--deep-link-cwd-b64":                  true,
	"--deep-link-last-fetch":               true,
	"--deep-link-repo":                     true,
	"--effort":                             true,
	"--environment":                        true,
	"--fallback-model":                     true,
	"--forward-home-settings":              true,
	"--inherit-permission-mode":            true,
	"--json-schema":                        true,
	"--managed-settings":                   true,
	"--max-budget-usd":                     true,
	"--max-thinking-tokens":                true,
	"--max-turns":                          true,
	"--messaging-socket-path":              true,
	"--model":                              true,
	"--name":                               true,
	"--on-branch":                          true,
	"--parent-session-id":                  true,
	"--permission-mode":                    true,
	"--permission-prompt-tool":             true,
	"--permission-prompts":                 true,
	"--plan-mode-instructions":             true,
	"--plugin-dir":                         true,
	"--plugin-dir-no-mcp":                  true,
	"--plugin-url":                         true,
	"--pool":                               true,
	"--prefill":                            true,
	"--prefill-b64":                        true,
	"--ref":                                true,
	"--remote-control-session-name-prefix": true,
	"--resume-drops-turn":                  true,
	"--resume-session-at":                  true,
	"--rewind-files":                       true,
	"--sdk-url":                            true,
	"--session-id":                         true,
	"--setting-sources":                    true,
	"--settings":                           true,
	"--system-prompt":                      true,
	"--system-prompt-file":                 true,
	"--system-prompt-snapshot":             true,
	"--task-budget":                        true,
	"--team-name":                          true,
	"--teammate-mode":                      true,
	"--thinking":                           true,
	"--thinking-display":                   true,
	"--watch-artifact":                     true,
	"--watch-artifact-no-autoreact":        true,
	"--workload":                           true,
	"-n":                                   true,
}

// forwardVariadic: consume following tokens until the next leading-dash token.
var forwardVariadic = map[string]bool{
	"--add-dir":       true,
	"--allowed-tools": true,
	"--allowedTools":  true,
	"--betas":         true,
	"--channels":      true,
	"--dangerously-load-development-channels": true,
	"--disallowed-tools":                      true,
	"--disallowedTools":                       true,
	"--file":                                  true,
	"--mcp-config":                            true,
	"--tools":                                 true,
}

// forwardOptionalValue: consume the next token only if it is not a leading-dash flag.
var forwardOptionalValue = map[string]bool{
	"--cloud":              true,
	"--debug":              true,
	"--from-pr":            true,
	"--prompt-suggestions": true,
	"--rc":                 true,
	"--remote-control":     true,
	"--resume":             true,
	"--teleport":           true,
	"--worktree":           true,
	"-d":                   true,
	"-r":                   true,
	"-w":                   true,
}
